export const ICONS = {
    email: require('../../assets/email.png'),
    password: require('../../assets/password.png'),
    close: require('../../assets/ic_close.png'),
    back: require('../../assets/ic_back.png'),
    list: require('../../assets/ic_list.png'),
    home: require('../../assets/ic_home.png'),
    like: require('../../assets/ic_favorite.png'),
    like2: require('../../assets/ic_like2.png'),
    shopping: require('../../assets/cart.png'),
    user: require('../../assets/ic_user.png'),
    search: require('../../assets/ic_search.png'),
    menu: require('../../assets/ic_menu.png'),
    notification: require('../../assets/ic_notification.png'),
    bookmark: require('../../assets/ic_bookmark.png'),
    dot: require('../../assets/ic_dot.png'),
    plus: require('../../assets/ic_plus.png'),
    minus: require('../../assets/ic_minus.png'),
    delete: require('../../assets/ic_delete.png'),
    eyeon: require('../../assets/eyeon.png'),
    eyeoff: require('../../assets/eyeoff.png'),
    facebook: require('../../assets/ic_facebook.png'),
    google: require('../../assets/ic_google.png'),
    location: require('../../assets/ic_location.png'),
    order: require('../../assets/ic_order.png'),
    clock: require('../../assets/ic_clock.png'),
    tune: require('../../assets/ic_tune.png'),

}